
#branches:
 # only:
  #  - master  # ветка git

# build: off  # будем использовать свой скрипт сборки

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test --info
      - name: Build with Gradle
        run: ./artifacts/app-mbank.jar &
